---
name: dependency-check-gradle

on:
  workflow_call:
    inputs:
      notify_slack:
        description: Whether to fire off a slack notification if the dependency-check report fails, such as a detected CVE hitting the CVSS threshold.
        type: boolean
        default: true
        required: false
      upload_artifact:
        description: Whether to upload the generated dependency-check report as an artifact to the GitHub Action job run.
        type: boolean
        default: true
        required: false
      setup_google_cloud_auth:
        description: Whether to attempt setting up google cloud auth. Namely, for pulling artifacts from a Google Registry.
        type: boolean
        default: true
        required: false
      slack_channel:
        description: Slack channel to post notification in the event of failure.
        type: string
        default: vulnerability-alerts
        required: false
    secrets:
      slack_bot_token:
        description: Access token for posting slack messages
        required: false
      google_cloud_service_account_key:
        description: Optional Google Cloud service account key, assuming setup_google_cloud_auth is passed as true.
        required: false

env:
  GRADLE_SWITCHES: --console=plain --info --warning-mode=all

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: "gradle"
      - uses: google-github-actions/auth@v0
        if: inputs.setup_google_cloud_auth
        with:
          credentials_json: ${{ secrets.google_cloud_service_account_key }}
      - uses: google-github-actions/setup-gcloud@v0.6.0
        if: inputs.setup_google_cloud_auth
      - name: dependency-check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} dependencyCheckAggregate
      - uses: actions/upload-artifact@v3
        if: always() && inputs.upload_artifact
        with:
          name: dependency-check-report
          path: build/reports
      - name: Send notification of failure to Slack
        if: failure() && inputs.notify_slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ inputs.slack_channel }}
          slack-message: "Dependency check vulnerability report for ${{ github.repository }}: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
